name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:    # Optional: allows manual sync trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Fork
        uses: tgymnich/fork-sync@v1
        with:
          owner: DevLM7         # Replace with the **original repo owner's username**
          repo: ChaloChalein2   # Replace with the **original repo name**
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: '*'           # Sync all branches
